### ISSUE TITLE
the model weight of Physformer

### ISSUE THREAD

**Issue by Snopylz** [KegangWangCCNU/PhysBench#10]
Hello, first of all, thank you very much for your open-source code! 
It seems that you are involved in the Physformer model here. I met the question that the rppg shape is really strange，from the Physformer‘s github code：https://github.com/ZitongYu/PhysFormer/issues/21

Do you have the model weight of  Physformer trained by yourself and how can I use it?

Thanks for sharing!!!

**Comment by KegangWangCCNU** [comment]
Due to GitHub's file size limitations, I am unable to upload the PhysFormer weights here. If you still need them, you can send me an email.
