### ISSUE TITLE
Data Usage Agreement

### ISSUE THREAD

**Issue by Promisery** [KegangWangCCNU/PhysBench#2]
Can you upload a template file of the Data Usage Agreement for RLAP? Thanks.

**Comment by KegangWangCCNU** [comment]
Hello, our dataset is ready for release, but the school's IRB approval has not been issued yet. The earliest possible date is June 11th. Once we obtain permission, we will immediately release the dataset.

**Comment by KegangWangCCNU** [comment]
Hello, all IRB processes have been completed, and the dataset can be released. Please visit our dataset Repo to obtain the data usage agreement. 

https://github.com/KegangWangCCNU/RLAP-dataset
