### ISSUE TITLE
inference using other models

### ISSUE THREAD

**Issue by Fouadbtlb** [KegangWangCCNU/PhysBench#6]
hi, 
thanks for you work.
i was wondering if there is a way to get inference using physformer, i tried but it s kinda complicated, can you help , thanks

**Comment by KegangWangCCNU** [comment]
Hi, let me know what help you need.

**Comment by amishparekh** [comment]
Hi, I am trying to use other models to get inference but running into errors maybe because of incorrect input shape.. I am trying to use TS-CAN_SCAMPS.h5 weights could you help me out in what different i need to do to make sure I am able to get bvp signal? also is the bvp signal obtained already filtered or do I need to do the post processing steps.. ?

**Comment by KegangWangCCNU** [comment]
@amishparekh @Fouadbtlb 

I understand the difficulties you are facing. I will supplement this work, please come back in a few days to check.

**Comment by KegangWangCCNU** [comment]
Hello, forgive my late update.

inference.py has been updated; it now supports eight models: seq, tscan, deepphys, efficientphys, physnet, chrom, pos, and ica, and allows for specifying weights as well as visualizing waveforms.

Please read the readme to understand how to use it.

If you encounter any issues during use, feel free to send an email or submit an issue!

**Comment by amishparekh** [comment]
@KegangWangCCNU 
Thanks a lot! I got it where I was doing it wrong..

**Comment by photondestroyer** [comment]
@amishparekh  hey, can you send me the pretrained model for physformer model, i am getting error while trying it myself and i cant find what i am doing wrong, now I just want to test it on UBFC before training it

**Comment by amishparekh** [comment]
@photondestroyer I haven't trained the physformer model.. you could look at https://github.com/ubicomplab/rPPG-Toolbox/tree/main/final_model_release There is a pretrained physformer model here.
