### ISSUE TITLE
A question about conference.py

### ISSUE THREAD

**Issue by LiuZeLan** [KegangWangCCNU/PhysBench#8]
Hello, first of all, thank you very much for your open-source code! I am a student and I need to refer to your code recently. I have a question about your code.
`model = EP()
model.build(input_shape=(None, 450, 8, 8, 3))
model.load_weights(args.weights)`
I would like to use EfficientPhys here. How can I modify the code？

**Comment by KegangWangCCNU** [comment]
I am currently working on it, please check back in a few days, I will release new code to address these issues.

**Comment by KegangWangCCNU** [comment]
Hello, forgive my late update.

`inference.py` has been updated; it now supports eight models: `seq`, `tscan`, `deepphys`, `efficientphys`, `physnet`, `chrom`, `pos`, and `ica`, and allows for specifying weights as well as visualizing waveforms.

Please read the `readme` to understand how to use it.

If you encounter any issues during use, feel free to send an email or submit an issue!
