### ISSUE TITLE
A question of EfficientPhys

### ISSUE THREAD

**Issue by LiuZeLan** [KegangWangCCNU/PhysBench#9]
Hello, first of all, thank you very much for your open-source code! Hello! It seems that you are involved in the EfficientPhys module here. Do you have the source code for EfficientPhys?

**Comment by KegangWangCCNU** [comment]
I think the new `inference.py` should be able to solve your problem. The model name corresponding to EfficientPhys is "EP," which is an abbreviation.

**Comment by LiuZeLan** [comment]
Thank you very much for your help.
